version: '3.3'

services:
  stability-ai:
    container_name: sd
    ports:
      - '5000:5000'
    image: 'r8.im/stability-ai/stable-diffusion@sha256:be04660a5b93ef2aff61e3668dedb4cbeb14941e62a3fd5998364a32d613e35e'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
  stable-diffusion-api:
    container_name: sd-api
    ports:
      - '9000:9000'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - stability-ai
  # stable-diffusion-ui:
  #   container_name: sd-vui
  #   ports:
  #     - '9000:3000'
  #   build:
  #     context: ./frontend
  #     dockerfile: Frontent.Dockerfile
  #   depends_on:
  #     - stability-ai

networks:
  default: